apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-db-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mytododb;
    CREATE USER 'todo_user'@'%' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON mytododb.* TO 'todo_user'@'%';
    FLUSH PRIVILEGES;
