apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: komalvede/todo-app:latest   # docker build करून push केलेलं image इथे द्यायचं
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: todo-db-service   # Service name वापरलाय
            - name: DB_USER
              value: todo_user
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: mytododb
