apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
spec:
  type: {{ .Values.service.appType | default "NodePort" }}
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port | default 5000 }}
      nodePort: {{ .Values.service.appNodePort | default 30081 }}

