---
apiVersion: v1
kind: Service
metadata:
  name: pgdb2
  labels:
    app: postgres2
    tier: database
spec:
  ports:
    - port: 5432
  selector:
    app: postgres2
    tier: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres2-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: postgres2
    tier: database
spec:
  accessModes:
    - ReadWriteMany   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 100Mi   #This will tell kubernetes about the amount of space we are trying to claim.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres2
  labels:
    app: postgres2
    tier: database
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: postgres2
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: postgres2
        tier: database
    spec:
      containers:
        - name: postgres2
          image: postgres
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: POSTGRES_DB # Setting Database Name from a 'ConfigMap'
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name2
          ports:
            - containerPort: 5432
              name: postgres2
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres2-persistance-storage
      volumes:
        - name: postgres2-persistance-storage
          persistentVolumeClaim:
            claimName: postgres2-pv-claim